language: "python"
python:
  - "3.5"
sudo: "required"
services:
  - docker
env:
  global:
    - DOCKER_REPOSITORY="mkobit/nifi"
    - DOCKER_USERNAME="mkobit"
  matrix:
    - >-
      TEMPLATE_FILE="templates/Dockerfile-template"
      BASE_IMAGE="java:7"
      GIT_TAG_NAME="nifi-0.5.1"
      DOCKER_TAGS="0.5.1-openjdk-7,latest"
      TEMPLATE_VALUES="base_image=java:7,nifi_version=0.5.1"
      DESTINATION="0.5.1-openjdk-7"
    - >-
      TEMPLATE_FILE="templates/Dockerfile-template"
      BASE_IMAGE="java:8"
      GIT_TAG_NAME="nifi-0.5.1"
      DOCKER_TAGS="0.5.1-openjdk-8,latest"
      TEMPLATE_VALUES="base_image=java:8,nifi_version=0.5.1"
      DESTINATION="0.5.1-openjdk-8"
before_script: ./make_docker.py -h
script: >-
  ./make_docker.py push
  --template-file $TEMPLATE_FILE
  --template-substitutions $TEMPLATE_VALUES
  --destination-file $DESTINATION
  --repository $DOCKER_REPOSITORY
  --tags $DOCKER_TAGS
  --username $DOCKER_USERNAME
  --email $DOCKER_EMAIL
  --password $DOCKER_PASSWORD
