language: "python"
python:
  - "3.5"
sudo: "required"
services:
  - docker
install: "pip install -r requirements.txt"
env:
  matrix:
    - TEMPLATE_FILE="templates/Dockerfile-template" BASE_IMAGE="java:8" GIT_TAG_NAME="nifi-0.5.1" DOCKER_TAGS="0.5.0-openjdk-8,latest"
script: make_docker.py --repository mkobit/nifi --no-docker-build --no-docker-push
