language: "python"
python:
  - "3.5"
sudo: "required"
services:
  - docker
env:
  matrix:
    - >-
      TEMPLATE_FILE="templates/Dockerfile-template"
      BASE_IMAGE="java:7"
      GIT_TAG_NAME="nifi-0.5.1"
      DOCKER_TAGS="0.5.1-openjdk-7,latest"
      TEMPLATE_VALUES="base_image=java:7,nifi_version=0.5.1"
      DESTINATION="0.5.1-openjdk-7"
    - >-
      TEMPLATE_FILE="templates/Dockerfile-template"
      BASE_IMAGE="java:8"
      GIT_TAG_NAME="nifi-0.5.1"
      DOCKER_TAGS="0.5.1-openjdk-8,latest"
      TEMPLATE_VALUES="base_image=java:8,nifi_version=0.5.1"
      DESTINATION="0.5.1-openjdk-8"
before_script: ./make_docker.py -h
script: >-
  ./make_docker.py
  --repository mkobit/nifi
  --templateFile $TEMPLATE_FILE
  --templateSubstitutions $TEMPLATE_VALUES
  --destinationFile $DESTINATION
  --no-docker-build
  --no-docker-push
