sudo: required
language: bash
services:
  - docker
install: true
env:
  global:
    - IMAGE_NAME=mkobit/nifi
  matrix:
    - BASE_IMAGE="java:8" NIFI_VERSION="0.2.1" TAG_NAMES="0.2.1"
    - BASE_IMAGE="java:8" NIFI_VERSION="0.3.0" TAG_NAMES="0.3.0"
    - BASE_IMAGE="java:7" NIFI_VERSION="0.4.0" TAG_NAMES="0.4.0-openjdk-7"
    - BASE_IMAGE="java:8" NIFI_VERSION="0.4.0" TAG_NAMES="0.4.0-openjdk-8"
    - BASE_IMAGE="java:9" NIFI_VERSION="0.4.0" TAG_NAMES="0.4.0-openjdk-9"
    - BASE_IMAGE="airdock/oracle-jdk:1.7" NIFI_VERSION="0.4.0" TAG_NAMES="0.4.0-oracle-java7"
    - BASE_IMAGE="airdock/oracle-jdk:1.8" NIFI_VERSION="0.4.0" TAG_NAMES="0.4.0-oracle-java8"
    - BASE_IMAGE="java:7" NIFI_VERSION="0.4.1" TAG_NAMES="0.4.1-openjdk-7"
    - BASE_IMAGE="java:8" NIFI_VERSION="0.4.1" TAG_NAMES="0.4.1-oracle-java8, 0.4, latest"
    - BASE_IMAGE="java:9" NIFI_VERSION="0.4.1" TAG_NAMES="0.4.1-openjdk-9"
    - BASE_IMAGE="airdock/oracle-jdk:1.7" NIFI_VERSION="0.4.1" TAG_NAMES="0.4.1-oracle-java7"
    - BASE_IMAGE="airdock/oracle-jdk:1.8" NIFI_VERSION="0.4.1" TAG_NAMES="0.4.1-oracle-java8"
